# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DisplayIOSwiftSampleApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DisplayIOSwiftSampleApp
  pod 'DIOSDK', '2.8.2'

  target 'DisplayIOSwiftSampleAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
